version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: zenn-cli
    versions:
    - 0.1.72
    - 0.1.73
    - 0.1.74
    - 0.1.78
  - dependency-name: textlint
    versions:
    - 11.8.2
